### Get all orders
GET http://localhost:3000/api/orders/

### Get one order by ID
GET http://localhost:3000/api/orders/6863acd3b0aaf7a0dfb5128e

### Create a new order
POST http://localhost:3000/api/orders/
Content-Type: application/json

{
  "payment_reference": "ord_123456789",
  "payment_provider": "paypal",
  "shipping_address": "4 Privet Drive, Little Whinging, Surrey"
}

### Update an existing order
PUT http://localhost:3000/api/orders/6863acd3b0aaf7a0dfb5128e
Content-Type: application/json

{
  "payment_reference": "ord_987654321",
  "payment_provider": "stripe",
  "shipping_address": "The Burrow, Ottery St. Catchpole"
}

### Pay an existing order
PATCH http://localhost:3000/api/orders/6863acd3b0aaf7a0dfb5128e/pay/
Content-Type: application/json

### Dispatch an existing order
PATCH http://localhost:3000/api/orders/6863acd3b0aaf7a0dfb5128e/dispatch/
Content-Type: application/json

### Deliver an existing order
PATCH http://localhost:3000/api/orders/6863acd3b0aaf7a0dfb5128e/deliver/
Content-Type: application/json

### Complete an existing order
PATCH http://localhost:3000/api/orders/6863acd3b0aaf7a0dfb5128e/complete/
Content-Type: application/json

### Cancel an existing order
PATCH http://localhost:3000/api/orders/6863acd3b0aaf7a0dfb5128e/cancel/
Content-Type: application/json


### Refund an existing order
PATCH http://localhost:3000/api/orders/6863acd3b0aaf7a0dfb5128e/refund/
Content-Type: application/json

### Add a review to a complete order
PATCH http://localhost:3000/api/orders/6863acd3b0aaf7a0dfb5128e/review/
Content-Type: application/json

{
  "review": "Excellent wand! My spells have never been more accurate."
}

### Delete order
DELETE http://localhost:3000/api/orders/6863acd3b0aaf7a0dfb5128e