### Get all tests
GET http://localhost:3000/api/tests

### Get one test by ID
GET http://localhost:3000/api/tests/68330e7503f0d4d3a6021aeb

### Create a new test
POST http://localhost:3000/api/tests/
Content-Type: application/json

{
  "name": "Advanced Spellcasting",
  "date": "2025-07-15T10:00:00.000Z"
}

### Update an existing test
PUT http://localhost:3000/api/tests/68330e7503f0d4d3a6021aeb
Content-Type: application/json

{
  "name": "Intermediate Potion Making",
  "date": "2025-08-20T14:30:00.000Z"
}

### Delete a test
DELETE http://localhost:3000/api/tests/68330e7503f0d4d3a6021aeb