### Get all cores
GET http://localhost:3000/api/cores?page=1&pageSize=5

### Get one wood by ID
GET http://localhost:3000/api/cores/686876537ae52f25a89ca4d5

### Find a core by name
GET http://localhost:3000/api/cores/name/veela%20hair

### Create a new core
POST http://localhost:3000/api/cores/
Content-Type: application/json

{
  "name": "Dragon heartstring",
  "description": "Dragon heartstring wands produced the most powerful and flamboyant magic and they learned spells faster and easier, however they were more prone to accidents. They were the most likely to change loyalty, but would always bond strongly with its current owner. It was also the easiest to turn to the dark arts, though it would not turn on its own.",
  "price": 400
}

### Update an existing core
PUT http://localhost:3000/api/cores/6869049884656d883f79c22a
Content-Type: application/json

{
  "name": "Unicorn hair",
  "description": "Unicorn hair wands were not very powerful, but they were the least prone to accidents and the least likely to change loyalties. They were also the most difficult to turn to the dark arts. They were prone to wilting if mishandled.",
  "price": 175
}

### Delete a core
DELETE http://localhost:3000/api/cores/68691bcb4e73ad09c1b0de32
