### Get all schools
GET http://localhost:3000/api/schools

### Get one school by ID
GET http://localhost:3000/api/schools/681a5877757f26d3b364cef2

### Create a new school
POST http://localhost:3000/api/schools/
Content-Type: application/json

{
    "name": "Hogwarts School of Witchcraft and Wizardry",
    "email": "hogwarts@magic.com",
    "address": "Magic Street 123",
    "phone": "123456789"
}

### Update an existing school
PUT http://localhost:3000/api/schools/681a5877757f26d3b364cef2
Content-Type: application/json

{
    "name": "Ilvermorny School of Witchcraft and Wizardry",
    "email": "ilvermorny@magic.com",
    "address": "Enchanted Avenue 456",
    "phone": "987654321"
}

### Delete a school
DELETE http://localhost:3000/api/schools/681a5877757f26d3b364cef2