### Get all wizards
GET http://localhost:3000/api/wizards 

### Get one wizard by ID
GET http://localhost:3000/api/wizards/686504f8cc6d7ba855a9575d

### Create wizard
POST http://localhost:3000/api/wizards/
Content-Type: application/json

{
    "username": "dracomalfoy",
    "password": "expelio123",
    "name": "Draco",
    "last_name": "Malfoy",
    "email": "draco.malfoy@hogwarts.edu",
    "phone": "445345678",
    "address": "5 Manor Drive, Malfoy Manor",
    "role": "WIZARD"
}


### Update wizard
PUT http://localhost:3000/api/wizards/686504f8cc6d7ba855a9575d
Content-Type: application/json

{
    "username": "harrypotter",
    "name": "Harry",
    "last_name": "Potter",
    "email": "harry.potter@hogwarts.edu",
    "phone": "5551234567",
    "address": "12 Grimmauld Place",
    "role": "WIZARD"
}

### Login
POST http://localhost:3000/api/wizards/login
Content-Type: application/json

{
    "username": "harrypotter",
    "password": "expelliarmus123"
}

### Reset password
PATCH http://localhost:3000/api/wizards/66fd592821f0f4df023497b5
Content-Type: application/json

{
    "newPassword": "alohomora456"
}

### Delete wizard
DELETE http://localhost:3000/api/wizards/686504f8cc6d7ba855a9575d