### Get all wizards
GET http://localhost:3000/api/wizards?page=1&pageSize=5

### Get one wizard by ID
GET http://localhost:3000/api/wizards/68698280a91cb51622ab22b6

### Get one wizard by email
GET http://localhost:3000/api/wizards/email/draco.malfoy@hogwarts.edu

### Get one wizard by username
GET http://localhost:3000/api/wizards/username/dracomalfoy

### Get if a wizard username is available
GET http://localhost:3000/api/wizards/available/username/dracomalfoy

### Get if a wizard email is available
GET http://localhost:3000/api/wizards/available/email/draco.malfoy@hogwarts.edu

### Create a new wizard
POST http://localhost:3000/api/wizards/
Content-Type: application/json

{
  "username": "dracomalfoy",
  "password": "Expelio123#@",
  "name": "Hayy",
  "last_name": "Malfoy",
  "email": "draco.malfoy@hogwarts.edu",
  "address": "5 Manor Drive, Malfoy Manor",
  "phone": "445345678",
  "school": "686f8a46968a4fc88cf2e758"
}

### Login to a wizard account
POST http://localhost:3000/api/wizards/login/
Content-Type: application/json

{
  "username": "dracomalfoy",
  "password": "Expelio123#@"
}

### Validate a wizard's password
POST http://localhost:3000/api/wizards/validate/6869a017667eb044d20917ed
Content-Type: application/json

{
  "password": "Expelio123#@"
}

### Update an existing wizard
PUT http://localhost:3000/api/wizards/686aa814867bf56ce7c5351e
Content-Type: application/json

{
  "username": "hermionegranger",
  "password": "Leviooooossaaa@@2",
  "name": "Hermione",
  "last_name": "Granger",
  "email": "Hermione.Granger@hogwarts.edu",
  "address": "50 Enchanted Lane, Hogwarts",
  "phone": "695123456",
  "school": "686b0408eb491423f1c68825"
}

### Change a wizard's password
PATCH http://localhost:3000/api/wizards/6869a017667eb044d20917ed
Content-Type: application/json

{
  "password": "Alohooooomora456$$"
}

### Make a wizard an admin
PATCH http://localhost:3000/api/wizards/686aa814867bf56ce7c5351e/admin

### Make an wizard a user
PATCH http://localhost:3000/api/wizards/686aa814867bf56ce7c5351e/user

### Deactivate a wizard account
PATCH http://localhost:3000/api/wizards/686a99c88d35246deb7b8fac/deactivate

### Activate a wizard account
PATCH http://localhost:3000/api/wizards/686a99c88d35246deb7b8fac/activate

### Delete wizard
DELETE http://localhost:3000/api/wizards/686f07849ce7415044acf3a4