### Get all woods
GET http://localhost:3000/api/woods

### Get one wood by ID
GET http://localhost:3000/api/woods/68548f06a38d38d62213055a

### Create a new wood
POST http://localhost:3000/api/woods/
Content-Type: application/json

{
    "name": "Alder wood",
    "binomial_name": "none",
    "description": "Alder wands are said to be suited to non-verbal spell work and are often associated with the most advanced witches and wizards",
    "price": 555555
}

### Update an existing wood
PUT http://localhost:3000/api/woods/68548f06a38d38d62213055a
Content-Type: application/json

{
    "name": "Alder wood",
    "binomial_name": "none",
    "description": "Alder wands are said to be suited to non-verbal spell work and are often associated with the most advanced witches and wizards",
    "price": 777777
}

### Delete a wood
DELETE http://localhost:3000/api/woods/68548bd2e5a2ed3827653956