### Get all quizzes
GET http://localhost:3000/api/quizzes

### Get one test by ID
GET http://localhost:3000/api/quizzes/68625b411ccf0f2835c9e75a

### Create a new test
POST http://localhost:3000/api/quizzes/
Content-Type: application/json

{
  "name": "Advanced Spellcasting",
  "date": "2025-07-15T10:00:00Z"
}

### Update an existing test
PUT http://localhost:3000/api/quizzes/68330e7503f0d4d3a6021aeb
Content-Type: application/json

{
  "name": "Intermediate Potion Making",
  "date": "2025-08-20T14:30:00Z"
}

### Delete a test
DELETE http://localhost:3000/api/quizzes/68330e7503f0d4d3a6021aeb