### Get all quizzes
GET http://localhost:3000/api/quizzes

### Get one quiz by ID
GET http://localhost:3000/api/quizzes/68625b411ccf0f2835c9e75a

### Create a new quiz
POST http://localhost:3000/api/quizzes/
Content-Type: application/json

{
  "name": "Advanced Spellcasting",
  "questions": ["686fac6fe5c1922fd703246d", "686fae3b65cba5a60140dfa6"]
}

### Update an existing quiz
PUT http://localhost:3000/api/quizzes/686b9b20f72a5a70ad8fc5ae
Content-Type: application/json

{
  "name": "Intermediate Potion Making",
  "questions": ["686e497ae9cae37589d37c9c", "686e497be9cae37589d37c9d"]
}

### Delete a quiz
DELETE http://localhost:3000/api/quizzes/686f058cc630c6c037fae637