### Get all questions
GET http://localhost:3000/api/questions

### Get one question by ID
GET http://localhost:3000/api/questions/68625794720b449b17e17e52

### Create a new question
POST http://localhost:3000/api/questions/
Content-Type: application/json

{
  "question": "What is your favorite wand type?",
  "options": ["Holly", "Elder", "Yew"]
}

### Update an existing question
PUT http://localhost:3000/api/questions/686b979441583c9dba2fd30c
Content-Type: application/json

{
  "question": "What is your preferred wand core?",
  "options": ["Phoenix Feather", "Dragon Heartstring", "Unicorn Hair"]
}

### Delete a question
DELETE http://localhost:3000/api/questions/686e497ae9cae37589d37c9c
