### Get all wands
GET http://localhost:3000/api/wands

### Get one wand by ID
GET http://localhost:3000/api/wands/68683ed4508f3212ea14e89a

### Create a new wand
POST http://localhost:3000/api/wands/
Content-Type: application/json

{
  "name": "Charles Weasley's first wand",
  "length_inches": 12,
  "description": "The most powerful wand in existence",
  "status": "active",
  "image": "https://example.com/elder-wand.jpg",
  "profit": 1000,
  "wood": "68691b824e73ad09c1b0de31",
  "core": "68691bcb4e73ad09c1b0de32"
}

### Update an existing wand
PUT http://localhost:3000/api/wands/68683ed4508eae12ea14e89a
Content-Type: application/json

{
  "name": "Phoenix Feather Wand",
  "length_inches": 11,
  "description": "A wand with a phoenix feather core",
  "status": "active",
  "image": "https://example.com/phoenix-wand.jpg",
  "profit": 500,
  "wood": "68691342a2b501ef3c6c6d81",
  "core": "6869049884656d883f79c22a"
}

### Deactivate a wand (logical removal)
PATCH http://localhost:3000/api/wands/68683ed4508f3212ea14e89a/deactivate

### Delete a wand
DELETE http://localhost:3000/api/wands/686919824e73ad09c1b0de2f
