### Get all wands
GET http://localhost:3000/api/wands

### Get one wand by ID
GET http://localhost:3000/api/wands/68683ed4508f3212ea14e89a

### Create a new wand
POST http://localhost:3000/api/wands/
Content-Type: application/json

{
  "name": "Elder Wand",
  "length": 15,
  "description": "The most powerful wand in existence",
  "status": "active",
  "image": "https://example.com/elder-wand.jpg",
  "profit_margin": 1000,
  "total_price": 5000,
  "wood": "68681375f9e4fcf1d48bf08f"
}

### Update an existing wand
PUT http://localhost:3000/api/wands/68683ed4508f3212ea14e89a
Content-Type: application/json

{
  "name": "Phoenix Feather Wand",
  "length": 11,
  "description": "A wand with a phoenix feather core",
  "status": "active",
  "image": "https://example.com/phoenix-wand.jpg",
  "profit_margin": 500,
  "total_price": 1500,
  "wood": "68681375f9e4fcf1d48bf08f"
}

### Deactivate a wand (logical removal)
PATCH http://localhost:3000/api/wands/68683ed4508f3212ea14e89a/deactivate

### Delete a wand
DELETE http://localhost:3000/api/wands/6867321425e64f49255e5a7e
